apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.12.2
        profile:
            VendorType: partner
            version: v1.2
        reportDigest: uint64:13965541712133318469
        chart-uri: https://charts.yugabyte.com/yugaware-openshift-2.18.2+1.tgz
        digests:
            chart: sha256:d0829973f9c561a4f6c2cf6307abbb950f081b340abedb9427b5c876df8bbe80
            package: 4f231b6acb820a8acc2e56718e8465fccf2edc601cea6ecad12de5208c908f52
        lastCertifiedTimestamp: "2023-09-13T07:53:47.337539+00:00"
        testedOpenShiftVersion: "4.11"
        supportedOpenShiftVersions: '>=4.4'
        webCatalogOnly: false
    chart:
        name: yugaware-openshift
        home: https://www.yugabyte.com
        sources: []
        version: 2.18.2+1
        description: YugabyteDB Anywhere provides deployment, orchestration, and monitoring for managing YugabyteDB clusters. YugabyteDB Anywhere can create a YugabyteDB cluster with multiple pods provided by Kubernetes or OpenShift and logically grouped together to form one logical distributed database.
        keywords: []
        maintainers:
            - name: Sanketh Indarapu
              email: sanketh@yugabyte.com
              url: ""
            - name: Govardhan Reddy Jalla
              email: gjalla@yugabyte.com
              url: ""
        icon: https://avatars0.githubusercontent.com/u/17074854?s=200&v=4
        apiversion: v2
        condition: ""
        tags: ""
        appversion: 2.18.2.1-b1
        deprecated: false
        annotations:
            charts.openshift.io/name: yugaware-openshift
        kubeversion: '>=1.17.0-0'
        dependencies: []
        type: ""
    chart-overrides: ""
results:
    - check: v1.0/contains-test
      type: Mandatory
      outcome: PASS
      reason: Chart test files exist
    - check: v1.1/has-kubeversion
      type: Mandatory
      outcome: PASS
      reason: Kubernetes version specified
    - check: v1.0/has-readme
      type: Mandatory
      outcome: PASS
      reason: Chart has a README
    - check: v1.0/helm-lint
      type: Mandatory
      outcome: PASS
      reason: Helm lint successful
    - check: v1.1/images-are-certified
      type: Mandatory
      outcome: PASS
      reason: |-
        Image certification skipped : registry.redhat.io/openshift4/ose-prometheus:v4.11.0
        Image is Red Hat certified : quay.io/yugabyte/yugaware-ubi:2.18.2.1-b1
        Image certification skipped : registry.redhat.io/rhscl/postgresql-13-rhel7:1-88.1661531722
    - check: v1.0/not-contain-csi-objects
      type: Mandatory
      outcome: PASS
      reason: CSI objects do not exist
    - check: v1.0/required-annotations-present
      type: Mandatory
      outcome: PASS
      reason: All required annotations present
    - check: v1.0/chart-testing
      type: Mandatory
      outcome: PASS
      reason: Chart tests have passed
    - check: v1.0/signature-is-valid
      type: Mandatory
      outcome: SKIPPED
      reason: 'Chart is not signed : Signature verification not required'
    - check: v1.0/is-helm-v3
      type: Mandatory
      outcome: PASS
      reason: API version is V2, used in Helm 3
    - check: v1.0/not-contains-crds
      type: Mandatory
      outcome: PASS
      reason: Chart does not contain CRDs
    - check: v1.0/contains-values-schema
      type: Mandatory
      outcome: PASS
      reason: Values schema file exist
    - check: v1.0/contains-values
      type: Mandatory
      outcome: PASS
      reason: Values file exist